# Linear Algerba Using Python3 & Numpy

<h4>Matrix Basic Operations like</h4>

<ul>
<li>Row Vector
<li>Column Vector
<li>Additions
<li>Multiplications
<li>Transpose
<li>Identity


In [1]:
import numpy as np

In [2]:
# Row Vector or (1 x n) Matrix

x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [3]:
# Column Vector or (n x 1) Matrix

x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [4]:
# Square Matrix or (n x n) Matrix

x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# (m x n) Matrix

x = np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [6]:
# Shape of the Matrix

x = np.array([[1,2,3], [4,5,6], [7,8,9]])
shape = np.shape(x)

print(x)
print("\nShape : ", shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape :  (3, 3)


# Identity Matrix

In [7]:
# (n x n) Identity Matrix

x = np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random Matrix

In [8]:
# Generating (m x n) Random Matrix

x = np.random.randint(20, size=(3, 4))
print(x)

[[ 3 11  5 16]
 [13  3  5  6]
 [14  5  4 10]]


In [9]:
# Generating (n x n) Random Matrix

x = np.random.randint(20, size=(4, 4))
print(x)

[[ 4 10  5  5]
 [13  1  1  8]
 [13 17  1 10]
 [12  5  7 17]]


# Transpose of a Matrix

In [10]:
A = np.random.randint(20, size=(3, 4))

transpose = A.T

print(A)
print(transpose)

[[ 5 13  8  7]
 [11  5  6  2]
 [11  2  8 13]]
[[ 5 11 11]
 [13  5  2]
 [ 8  6  8]
 [ 7  2 13]]


# Matrix Addition

In [11]:
# Matrix Addition

a = np.random.randint(20, size=(4,4))
b = np.random.randint(20, size=(4,4))

sum = a + b
print("\na : \n", a)
print("\nb : \n", b)
print("\nsum : \n", sum)


a : 
 [[13  0 10  5]
 [ 0  9  7  7]
 [ 5  9  2  8]
 [ 4 11  8 19]]

b : 
 [[14 14 18 15]
 [13  6  1 15]
 [15 13  7  7]
 [19  6 13  9]]

sum : 
 [[27 14 28 20]
 [13 15  8 22]
 [20 22  9 15]
 [23 17 21 28]]


In [12]:
# Scalar Addition

a = np.random.randint(10, size=(3,3))
scalar = 5

scalar_sum = scalar + a

print("\nscalar : ", scalar)
print("\na : \n", a)
print("\nscalar_sum : \n", scalar_sum)


scalar :  5

a : 
 [[2 1 3]
 [2 3 5]
 [8 3 8]]

scalar_sum : 
 [[ 7  6  8]
 [ 7  8 10]
 [13  8 13]]


# Matrix Multiplication

In [13]:
# Matrix Multiplication

a = np.random.randint(6, size=(4,3))
b = np.random.randint(5, size=(3,5))

result_matrix = a.dot(b)
print("\na : \n", a)
print("\nb : \n", b)
print("\nresult : \n", result_matrix)
print("\nresult matrix shape : ", np.shape(result_matrix))


a : 
 [[4 0 1]
 [4 0 2]
 [3 5 4]
 [5 3 3]]

b : 
 [[3 0 1 0 1]
 [0 3 3 2 2]
 [2 1 0 1 4]]

result : 
 [[14  1  4  1  8]
 [16  2  4  2 12]
 [17 19 18 14 29]
 [21 12 14  9 23]]

result matrix shape :  (4, 5)


In [14]:
# Scalar Multiplication

a = np.random.randint(10, size=(3,3))
scalar = 5

result_matrix = scalar * a

print("\nscalar : ", scalar)
print("\na : \n", a)
print("\nresult : \n", result_matrix)
print("\nresult matrix shape : ", np.shape(result_matrix))


scalar :  5

a : 
 [[9 0 2]
 [1 4 9]
 [1 5 0]]

result : 
 [[45  0 10]
 [ 5 20 45]
 [ 5 25  0]]

result matrix shape :  (3, 3)


# Matrices mutliplication is distributive A(B+C)=AB+AC

In [15]:
A = np.random.randint(6, size=(2,3))
B = np.random.randint(5, size=(3,5))
C = np.random.randint(5, size=(3,5))

result1 = A.dot(B + C)
result2 = A.dot(B) + A.dot(C)

print("\nA : \n", A)
print("\nB : \n", B)
print("\nC : \n", C)

print("\nresult1 : \n", result1)
print("\nresult2 : \n", result2)

print("\n\nMatrix Multiplication is Distributive : ", np.array_equal(result1, result2))


A : 
 [[1 4 0]
 [1 0 1]]

B : 
 [[2 2 1 1 0]
 [4 0 3 1 4]
 [1 4 0 4 1]]

C : 
 [[3 4 3 2 1]
 [3 2 0 3 2]
 [4 2 1 0 1]]

result1 : 
 [[33 14 16 19 25]
 [10 12  5  7  3]]

result2 : 
 [[33 14 16 19 25]
 [10 12  5  7  3]]


Matrix Multiplication is Distributive :  True


# Matrices mutliplication is associative A(BC)=(AB)C

In [16]:
A = np.random.randint(6, size=(3,5))
B = np.random.randint(5, size=(5,3))
C = np.random.randint(5, size=(3,4))

result1 = A.dot(np.dot(B, C))
result2 = (np.dot(A,B)).dot(C)

print("\nA : \n", A)
print("\nB : \n", B)
print("\nC : \n", C)

print("\nresult1 : \n", result1)
print("\nresult2 : \n", result2)

print("\n\nMatrix Multiplication is Associative : ", np.array_equal(result1, result2))


A : 
 [[5 4 2 2 4]
 [0 1 5 5 0]
 [5 3 1 1 5]]

B : 
 [[0 3 2]
 [3 3 2]
 [2 4 2]
 [4 0 0]
 [1 0 1]]

C : 
 [[3 0 1 3]
 [2 4 1 3]
 [4 0 4 1]]

result1 : 
 [[258 140 167 215]
 [193  92 104 180]
 [208 112 140 167]]

result2 : 
 [[258 140 167 215]
 [193  92 104 180]
 [208 112 140 167]]


Matrix Multiplication is Associative :  True


# Matrix multiplication is not commutative AB≠BA

In [17]:
A = np.random.randint(6, size=(3,3))
B = np.random.randint(5, size=(3,3))

result1 = A.dot(B)
result2 = B.dot(A)

print("\nA : \n", A)
print("\nB : \n", B)

print("\nresult1 : \n", result1)
print("\nresult2 : \n", result2)

print("\n\nMatrix Multiplication is Commutative : ", np.array_equal(result1, result2))


A : 
 [[1 4 1]
 [1 5 0]
 [1 3 4]]

B : 
 [[4 1 2]
 [1 0 4]
 [0 2 0]]

result1 : 
 [[ 8  3 18]
 [ 9  1 22]
 [ 7  9 14]]

result2 : 
 [[ 7 27 12]
 [ 5 16 17]
 [ 2 10  0]]


Matrix Multiplication is Commutative :  False


# Matrix Inversion

In [18]:
A = np.random.randint(6, size=(3,3))

inverse = np.linalg.inv(x)

print("\nA : \n", A)
print("\nInverse : \n", inverse)


A : 
 [[1 3 4]
 [3 4 1]
 [4 5 4]]

Inverse : 
 [[ 0.08599168  0.16019417 -0.03675451 -0.07905687]
 [ 0.02191401 -0.04466019  0.05353675 -0.01692094]
 [ 0.26269071  0.1038835  -0.14937587 -0.03828017]
 [-0.17531207 -0.14271845  0.07170596  0.13536755]]


# Upper Triangualr Matrix

In [19]:
A = np.random.randint(6, size=(4,4))
upper = np.triu(A, 0)

print("\nA : \n", A)
print("\nUpper : \n", upper)


A : 
 [[1 2 1 1]
 [5 3 0 4]
 [3 0 4 3]
 [0 0 0 0]]

Upper : 
 [[1 2 1 1]
 [0 3 0 4]
 [0 0 4 3]
 [0 0 0 0]]


# Lower Triangular Matrix

In [20]:
A = np.random.randint(6, size=(4,4))
lower = np.tril(A, 0)

print("\nA : \n", A)
print("\nLower : \n", lower)


A : 
 [[2 1 5 3]
 [1 5 5 0]
 [2 3 3 3]
 [0 0 1 0]]

Lower : 
 [[2 0 0 0]
 [1 5 0 0]
 [2 3 3 0]
 [0 0 1 0]]


# References:

https://en.wikipedia.org/wiki/Matrix_(mathematics)

https://en.wikipedia.org/wiki/Matrix_multiplication

https://docs.scipy.org/doc/numpy/user/quickstart.html